[package]
name = "binutils"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
tempfile.workspace = true
tracing.workspace = true