[workspace]
resolver = "2"
members = ["binutils", "sim_macro", "sim", "debugger", "grader"]

[workspace.package]
repository = "https://github.com/sshwy/y86-pipe-rs"

[workspace.dependencies]
tempfile = "3.12.0"
tracing = "0.1"
anyhow = "1.0"
